name: Deploy to GCP

on:
  push:
    branches:
      - master

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-southeast2
  REPOSITORY: presensee-repo
  SERVICE_NAME: ${{ secrets.GCP_PROJECT_ID }}
  DB_INSTANCE: ${{ secrets.DB_NAME }}
  GCS_BUCKET_NAME: ${{secrets.GCS_BUCKET_NAME}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  DB_USER: ${{secrets.DB_USER}}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1 # Add this step
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Configure Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        env:
          IMAGE_URI: ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ secrets.GCP_PROJECT_ID }}:${{ github.sha }}
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run (Test)
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: test-service
          image: gcr.io/google-samples/hello-app:1.0
          region: ${{ env.REGION }}
